---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wg-easy
  annotations:
    nfs.io/storage-path: "data01/wg-easy/config"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
