apiVersion: v1
kind: Service
metadata:
  name: wg-easy-tcp
spec:
  type: ClusterIP
  ports:
    - port: 51821
      targetPort: wg-easy-tcp
      protocol: TCP
  selector:
    app: wg-easy
    part-of: wg-easy
---
kind: Service
apiVersion: v1
metadata:
  name: ak-outpost-proxy01
spec:
  type: ExternalName
  externalName: ak-outpost-proxy01.authentik.svc.cluster.local
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: wg-easy
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.61
  selector:
    app: wg-easy
    part-of: wg-easy
  ports:
    - port: 51820
      targetPort: wg-easy
      protocol: UDP
  allocateLoadBalancerNodePorts: false
